version: "3.9"
services:
  rtmp:
    build: ./rtmp
    ports:
     - "1935:1935"
     - "443:443"
     - "8088:8088"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls

  auth:
    build: ./auth
    container_name: auth_server

  cvedia-rt:
    build:
      context: ./cvedia-rt
    container_name: cvedia_rt_instance
    ports:
      - "8080:8080"
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock